### ISSUE TITLE
Any plan to support onboard mx150?

### ISSUE THREAD

**Issue by eebssk1** [LaneLyng/MobilePascalTDPTweaker#9]
Do you have any plan to support mx150 vbios?
it's integrated into system bios,but if you want to investigate,please remind me.
(i found two modules that look like vbios,but one can open but says unsupport,another one just can not open).

**Comment by LaneLyng** [comment]
Hi eebssk1. Last time I tried modifying the mx150's tdp, it didn't take any effect. If you can email me your mx150's vbios, I can take another look.

**Comment by eebssk1** [comment]
Ok,a email has sent to the address displayed on your profile.But unfortunately,my laptop has Intel BootGuard(level 3) enabled,the vbios section shows blue mark on UEFITool,so i don't know whether flash a modified system bios will brick it or not.......

**Comment by re23071998** [comment]
waiting...

**Comment by re23071998** [comment]
how to get vbios from my laptop btw? :D

**Comment by eebssk1** [comment]
@re23071998 Use Universal BIOS Backup tool to dump your system bios.Then use UEFI tool to extract VBIOS module.Note that there's a lot of modules in system bios.

**Comment by re23071998** [comment]
universal bios backup says "unsupported" or something I don't remember

**Comment by nariox** [comment]
Hi @LaneLyng : would sending you another MX150 bios help you at all?
Are the addresses/shifts reverse engineered or is there some documentation somewhere? I was able to enable the power limit slider on my BIOS, but that leaves it with 5001W power limit by default (probably because the values are not initialized in the original file).

**Comment by nariox** [comment]
In case it does help, attached is the BIOS:
https://www.dropbox.com/s/14kauaun1x1k3u3/mx150bios.rom?dl=0

And below is the report that `nvidia-smi -q` reports:
https://pastebin.com/Zz9ViHUz

For some reason, my vBIOS doesn't seem to be set up right (basically, the embedded controller will freak out if the GPU temp goes above 74C, but the GPU temps will happily climb to even higher temps, when that happens, the GPU becomes locked at around 300MHz until reboot or sleep). On Windows, somehow the profile is set to make 70C be the target temp, but not on Linux.

**Comment by eebssk1** [comment]
Closed due to inactivity (historitic issues cleanup).
